#!/bin/bash
# 查看端口使用情况，使用netstat命令。
# 查看已经连接的服务端口（ESTABLISHED
netstat -a
　
# 查看所有的服务端口（LISTEN，ESTABLISHED）
netstat -ap
 
# 查看8080端口，则可以结合grep命令：
netstat -ap | grep 8080
 
# 如查看8888端口，则在终端中输入：
lsof -i:8888
# 这个命令也可以查出是哪个 进程 在占用8888 端口
 
# 若要停止使用这个端口的程序，使用kill +对应的pid即可

