#!/bin/bash
##################################################################
## 1. nslookup 互动式地查询域名记录
##################################################################
nslookup facebook.github.io

##################################################################
## 2. dig 阮一峰 DNS 原理入门
##################################################################
dig math.stackexchange.com  # 会输出六段信息
# 第一段是查询参数和统计
# ; <<>> DiG 9.10.3-P4-Ubuntu <<>> math.stackexchange.com
# ;; global options: +cmd
# ;; Got answer:
# ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17428
# ;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 4, ADDITIONAL: 5

# 第二段是查询内容
# ;; OPT PSEUDOSECTION:
# ; EDNS: version: 0, flags:; udp: 4096
# ;; QUESTION SECTION:
# ;math.stackexchange.com.                IN      A
# 上面结果表示, 查询域名math.stackexchange.com的A记录, A是address的缩写

# 第三段是DNS服务器的答复
# ;; ANSWER SECTION:
# math.stackexchange.com. 300     IN      A       151.101.1.69
# math.stackexchange.com. 300     IN      A       151.101.65.69
# math.stackexchange.com. 300     IN      A       151.101.193.69
# math.stackexchange.com. 300     IN      A       151.101.129.69
# 上面结果显示, math.stackexchange.com有四个A记录, 即四个IP地址。300是TTL值（Time to live 的缩写）, 表示缓存时间, 即600秒之内不用重新查询

# 第四段显示stackexchange.com的NS记录（Name Server的缩写）, 即哪些服务器负责管理stackexchange.com的DNS记录
# ;; AUTHORITY SECTION:
# stackexchange.com.      169071  IN      NS      ns-1832.awsdns-37.co.uk.
# stackexchange.com.      169071  IN      NS      ns-1029.awsdns-00.org.
# stackexchange.com.      169071  IN      NS      ns-925.awsdns-51.net.
# stackexchange.com.      169071  IN      NS      ns-463.awsdns-57.com.
# 上面结果显示stackexchange.com共有四条NS记录, 即四个域名服务器, 向其中任一台查询就能知道math.stackexchange.com的IP地址是什么

# 第五段是上面四个域名服务器的IP地址, 这是随着前一段一起返回的
# ;; ADDITIONAL SECTION:
# ns-1029.awsdns-00.org.  137867  IN      A       205.251.196.5
# ns-1832.awsdns-37.co.uk. 138175 IN      A       205.251.199.40
# ns-463.awsdns-57.com.   139003  IN      A       205.251.193.207
# ns-925.awsdns-51.net.   139538  IN      A       205.251.195.157

# 第六段是DNS服务器的一些传输信息
# ;; Query time: 265 msec
# ;; SERVER: 127.0.1.1#53(127.0.1.1)
# ;; WHEN: Fri Dec 02 09:44:42 CST 2016
# ;; MSG SIZE  rcvd: 316
# 上面结果显示, 本机的DNS服务器是127.0.1.1, 查询端口是53（DNS服务器的默认端口）, 以及回应长度是316字节

dig +trace math.stackexchange.com
# 第一段列出根域名.的所有NS记录, 即所有根域名服务器
# 根据内置的根域名服务器IP地址, DNS服务器向所有这些IP地址发出查询请求, 询问math.stackexchange.com的顶级域名服务器com.的NS记录。最先回复的根域名服务器将被缓存, 以后只向这台服务器发请求
# ; <<>> DiG 9.10.3-P4-Ubuntu <<>> +trace math.stackexchange.com
# ;; global options: +cmd
# .                       481638  IN      NS      l.root-servers.net.
# .                       481638  IN      NS      d.root-servers.net.
# .                       481638  IN      NS      k.root-servers.net.
# .                       481638  IN      NS      g.root-servers.net.
# .                       481638  IN      NS      c.root-servers.net.
# .                       481638  IN      NS      a.root-servers.net.
# .                       481638  IN      NS      h.root-servers.net.
# .                       481638  IN      NS      e.root-servers.net.
# .                       481638  IN      NS      j.root-servers.net.
# .                       481638  IN      NS      b.root-servers.net.
# .                       481638  IN      NS      i.root-servers.net.
# .                       481638  IN      NS      m.root-servers.net.
# .                       481638  IN      NS      f.root-servers.net.
# .                       518400  IN      RRSIG   NS 8 0 518400 20161214170000 20161201160000 39291 . FF1AcmQKRPTMrEy5U5gaOhoO+7dk6sUB1SdzGWlt8bkXhqVY5kNnwmVG Nk3YsJWXKlI104HGbIZPwqA1btyokO9svD+zkqwtwbAPIXF741djW42/ EQEpl89OTTz8L0m4WYVUAdn6rSFKxcPlL/16DGmuhCJMTe2sBeGipN3u Bo06uZT7P5A60vi0+m7wq3Ymw+Ra8mlajZ+cDndL/sXs6M6QGn0Y0o6b A28UVf8nwsULhmu4jge5QBRaEfnGVJf6oX93bvbLJCfRpc0yEbPVBeO9 wozWRbFqs82vyO9SzHAUJfnnkdz93bKhu8Y3F+Rs3tetbO/0YPjG4S65 /IaUvg==
# ;; Received 1097 bytes from 127.0.1.1#53(127.0.1.1) in 1 ms

# 接着第二段
# ;; ANSWER SECTION:
# com.                    133713  IN      NS      a.gtld-servers.net.
# com.                    133713  IN      NS      f.gtld-servers.net.
# com.                    133713  IN      NS      b.gtld-servers.net.
# com.                    133713  IN      NS      e.gtld-servers.net.
# com.                    133713  IN      NS      l.gtld-servers.net.
# com.                    133713  IN      NS      g.gtld-servers.net.
# com.                    133713  IN      NS      d.gtld-servers.net.
# com.                    133713  IN      NS      m.gtld-servers.net.
# com.                    133713  IN      NS      c.gtld-servers.net.
# com.                    133713  IN      NS      k.gtld-servers.net.
# com.                    133713  IN      NS      j.gtld-servers.net.
# com.                    133713  IN      NS      i.gtld-servers.net.
# com.                    133713  IN      NS      h.gtld-servers.net.
# 然后, DNS服务器向这些顶级域名服务器发出查询请求, 询问math.stackexchange.com的次级域名stackexchange.com的NS记录。
# 然后, DNS服务器向上面这四台NS服务器查询math.stackexchange.com的主机名, 这里省去了

dig coder352.github.com +nostats +nocomments +nocmd
dig +short math.stackexchange.com
# 只返回math.stackexchange.com对应的4个IP地址（即A记录）
# 151.101.129.69
# 151.101.65.69
# 151.101.193.69
# 151.101.1.69

dig @8.8.8.8 math.stackexchange.com  # 指定 DNS 服务器
dig ns com
dig ns stackexchange.com  # 单独查看每一级域名的NS记录
dig +short ns com
dig +short ns stackexchange.com  # +short参数可以显示简化的结果。
dig -x 192.30.252.153  # 反查域名 153.252.30.192.in-addr.arpa. 3600 IN    PTR pages.github.com.
# 上面结果显示，192.30.252.153这台服务器的域名是pages.github.com, 逆向查询的一个应用，是可以防止垃圾邮件，即验证发送邮件的IP地址，是否真的有它所声称的域名

# dig命令可以查看指定的记录类型
dig a github.com
dig ns github.com
dig mx github.com

##################################################################
## 记录类型
##################################################################
#（1）A：地址记录（Address），返回域名指向的IP地址。
#（2）NS：域名服务器记录（Name Server），返回保存下一级域名信息的服务器地址。该记录只能设置为域名，不能设置为IP地址。
#（3）MX：邮件记录（Mail eXchange），返回接收电子邮件的服务器地址。
#（4）CNAME：规范名称记录（Canonical Name），返回另一个域名，即当前查询的域名是另一个域名的跳转，详见下文。
#（5）PTR：逆向查询记录（Pointer Record），只用于从IP地址查询域名，详见下文。
dig facebook.github.io  # facebook.github.io.     2775    IN      CNAME   github.map.fastly.net.

##################################################################
## 安恒杯
##################################################################
# Tips:域名的 NS dns.flag.sec.edu-info.edu.cn 当前 IP 地址为 202.112.26.110
# edns-client-subnet
dig @202.112.26.110 get.flag.sec.edu-info.edu.cn txt +subnet=8.8.8.8

##################################################################
## 3. host host命令可以看作dig命令的简化版本，返回当前请求域名的各种记录
## whois 命令用来查看域名的注册情况
##################################################################
host github.com
# github.com has address 192.30.252.121
# github.com mail is handled by 5 ALT2.ASPMX.L.GOOGLE.COM.
# github.com mail is handled by 10 ALT4.ASPMX.L.GOOGLE.COM.
# github.com mail is handled by 10 ALT3.ASPMX.L.GOOGLE.COM.
# github.com mail is handled by 5 ALT1.ASPMX.L.GOOGLE.COM.
# github.com mail is handled by 1 ASPMX.L.GOOGLE.COM.

host 192.30.252.153  # host命令也可以用于逆向查询，即从IP地址查询域名，等同于dig -x <ip>
whois github.com

##################################################################
## 4. tracepath
##################################################################
tracepath 8.8.8.8  # 可以看到自己外网 IP 对应的对面的 IP
curl ifconfig.me  # 看到自己的外网 IP

##################################################################
## 5. route
##################################################################
route  # 等同于 netstat -nr
# 第一行会显示路由器的 IP
ip route  # 更详细的信息

##################################################################
## 6. arp
##################################################################
arp -n  # 会显示 IP MAC
