#!/bin/bash

# 9x9 乘法表
for i in {1..12}; do for j in $(seq 1 $i); do echo -ne $i x $j=$((i*j))\t;done; echo;done

# Fork炸弹
# 这个命令其实是一个fork炸弹，它会以指数级的自乘，直到所有的系统资源都被利用了或者系统挂起
# （想要见识这个命令的威力你可以试一次这个命令，但是后果自负，记得在运行它之前关掉并保存其它所有程序和文件）
# (){:|:&}:

# 下面的”while“命令是一个脚本，这个脚本可以为你提供彩色的日期和文件直到你按下中断键（ctrl+c）。复制粘贴这个命令到你的终端
# 但好像不行了
while true; do echo "$(date '+%D %T' | toilet -f term -F border --gay)"; sleep 1; done
