#!/bin/bash
path=`pwd`
#sudo echo ". $path/myscript" 
sudo echo ". $path/myscript" >> /etc/bash.bashrc                                                   
sudo echo "export PATH=$path/bin:$PATH" >> /etc/bash.bashrc
