#!/bin/bash

##################################################################
## /etc/bash.bashrc
##################################################################
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
export PATH=/home/${USER}/github/jLife/bin:$PATH
export PATH=/home/${USER}/github/jShellscript/bin:$PATH
export PATH=/home/${USER}/github/jShellscript/bin/ctf:$PATH
export PATH=/home/${USER}/github/jShellscript/bin/game:$PATH
export PATH=/home/${USER}/miniconda3/bin:$PATH                    # for miniconda
export PATH=/home/${USER}/github/jShellscript/bin/template:$PATH  # for python
export PATH=/home/${USER}/github/jShellscript/template:$PATH      # for shellscript
export PATH=/home/${USER}/github/jWeb/template:$PATH              # for html, css, js, jquery ...
export PATH=/home/${USER}/github/others/ctf-tools/bin:$PATH
export PATH=/usr/local/texlive/2016/bin/x86_64-linux:$PATH
export PYTHONPATH=$PYTHONPATH:/home/${USER}/github/jShellscript/bin/pythonpath
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export HISTCONTROL=ignorespace  # 前面带空格的命令不记录到历史
export WORKON_HOME=$HOME/.virtualenvs  # python-virtualenvwrapper 环境变量
export PROJECT_HOME=$HOME/workspace  # virtualenvwrapper 的工作路径, mkproject 使用
export PYENV_ROOT="$HOME/.pyenv"  # pyenv 用到的环境变量
export PATH=$PYENV_ROOT/bin:$PATH  # pyenv 可执行文件
eval "$(pyenv init -)"  # enable shims and autocompletion
# export LC_ALL="en_US.UTF-8"
# export LC_CTYPE="en_US.UTF-8"
export LC_CTYPE=zh_CN.UTF-8  # emacs GUI 输入中文要用这个, 终端里本来就可以输入中文, 放到 /etc/environment (Ubuntu 16.04 后才有的文件)
# export HTTP_PROXY='http://192.168.1.13:8080'  # 编辑 System Setting -> Network -> proxy 会自动保存到 /etc/environment
# 下面的 source 用 virtualenvwrapper 的时候取消注释, 用 miniconda3 的时候要注释掉
# source /usr/share/virtualenvwrapper/virtualenvwrapper.sh  # 这条命令之后才能使用 mkvirtualenv 等命令
# export EDITOR=vim  # 加上这个以后好多 emacs 的快捷键用不了

##################################################################
## UTF8
##################################################################
# 和 Docker 容器不兼容
# LANG="en_US.UTF-8"
# LC_COLLATE="en_US.UTF-8"
# LC_CTYPE="en_US.UTF-8"
# LC_MESSAGES="en_US.UTF-8"
# LC_MONETARY="en_US.UTF-8"
# LC_NUMERIC="en_US.UTF-8"
# LC_TIME="en_US.UTF-8"
# LC_ALL="en_US.UTF-8"

##################################################################
## Tmux 每次登陆进入到tmux
##################################################################
cmd=$(which tmux) # tmux path
if [ -z $cmd ]; then  # 判断是否已有开启的tmux会话，没有则开启
    echo "You need to install tmux."
    # exit 1
else
    session=`whoami`  # session name
    $cmd has -t $session  # has-session 不存在会报错, 并且返回 1, 存在返回 0
    if [ $? != 0 ]; then
        $cmd new -d -n normal -s $session            # 最后的 "" 中的都是命令
        # $cmd splitw -v -p 20 -t $session "pry"  # 创建窗口 1，并分为上下两个窗格，其中上窗格占 80% 空间，运行 Vim，下窗格占 20% 空间，运行 Pry
        # $cmd neww -n mutt -t $session "mutt"    # 创建窗口 2，运行 Mutt
        # 下面这句话并没有用
        $cmd set -g automatic-rename-format '#(pwd="#{pane_current_path}"; echo ${pwd####*/})'
        $cmd att -t $session                      # 第二个终端就不会进入 tmux 了, 最后才能进入 tmux
    fi
fi
# 另一种判断 tmux 是否已经运行的方法
# if which tmux 2>&1 >/dev/null; then
#     # test -z "$TMUX" && (tmux attach || tmux_init)  # attach 上以后会自动 sync
#     test -z "$TMUX" && (clear || tmux_init)  # 当打开第二个终端时, 不执行任何操作, tmux_init() 函数中可以写初始化
# fi

##################################################################
## django & virtualenv
##################################################################
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/workspace
# source /usr/local/bin/virtualenvwrapper.sh

##################################################################
## Go env
##################################################################
export GOPATH=$HOME/workspace
export PATH=$PATH:$GOPATH/bin

##################################################################
## ~/.zshrc see something in jpc/terminal_config
##################################################################
eval `dircolors ~/.dircolors` # 执行的是调用这个脚本的地方的文件，即 ~/.dircolors
# dircolors 是系统自带命令，dircolors文件是自定义的，只要加上这句话，就可以改变ls的颜色，不需要其它软件支持
export TERM=xterm-256color
DEFAULT_USER=`whoami`
export EDITOR=/usr/bin/vim

##################################################################
## Change Title of Terminal
##################################################################
function set-title(){
  if [[ -z "$ORIG" ]]; then
    ORIG=$PS1
  fi
  TITLE="\[\e]2;$*\a\]"
  PS1=${ORIG}${TITLE}
}
# set-title "路尽隐香处 翩然雪海间"
