#!/bin/bash
# alias 等号左右不能有空格
# oneko & # 打开终端出现一只小猫
# 变态的 oh-my-zsh 中有好多的 alias，又造轮子了 
########################################
## 系统操作 
########################################
alias cls="clear"
alias catms="cat ~/github/shellscript/myscript | more"
alias findname='find -iname'  # exapmle: findname "*.txt"
alias fy='sdcv -c'  # sudo apt-get install sdcv
export GREP_COLOR='01;37;46'   # color grep matches 蓝底白字加粗
alias grep="grep -i --color=always"
# grepf 在 PATH 里
alias greps="grep -rin --color=always"  # example: greps hell
alias grepsls='ls | grep'
alias dush='du -sh'  # 查看当前所在的目录的大小
alias llv='ll -v'
alias lsv='ls -v'
alias myip="ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v 192.168.56.1|grep -v inet6|awk '{print $2}'|tr -d 'addr:'"
alias nau='nautilus .'
alias netstatm='netstat -antp'
alias terminalnew='gnome-terminal --working-directory=`pwd`'
alias cman='LANG="zh_CN.utf8" man'
alias gj="echo '$mypassword' | sudo -S shutdown -h now"
# alias php="/opt/lampp/bin/php"
alias rmlatex="rm *.log *.aux *.pdf"
alias tcpdump='tcpdump -nn -XSltv'
alias nmapme='nmap localhost'  # sudo apt-get install nmap
# 这个unzip的参数只有ubuntu默认有
alias unzipo='unzip -O cp936'
alias unrarx='unrar x'  # 将rar解压到当前文件夹,全路径
alias xopen="xdg-open"
alias mmatlabr="matlab -nosplash -nodesktop -r"
alias mmatlab="matlab -nosplash -nodesktop"
# -nosplash表示不加载启动界面
# -nodesktop表示不加载GUI界面
# -r表示运行Matlab命令行（MATLAB_command）
# file_base_name表示文件名，但不包含文件扩展名

##################################################################
## Nginx PHP Server
##################################################################
alias cnginx='sudo nginx -p $PWD'
alias snginx='sudo nginx -s stop'
# Ubuntu 直接输入 可执行的 .py 文件不是执行它, 而是打开, 以前 14.04 还不是的啊
# alias mcurl='python ~/github/shellscript/bin/curl.py'  # 是下面的 py=vi 搞得鬼
# 开启 fgcgi, 用 nginx 和 php 时要开启
alias sfcgi='sudo /usr/bin/spawn-fcgi -a 127.0.0.1 -p 9000 -C 5 -u www-data -g www-data -f /usr/bin/php-cgi7.0 -P /var/run/fastcgi-php.pid' 
alias sphpserver='php -S localhost:9999'
alias phpserver='google-chrome http://localhost:9999/'
alias lnsphpmyadmin='sudo ln -s /usr/share/phpmyadmin /home/coder352/web/phpmyadmin'
alias logphpmyadmin='google-chrome localhost/phpmyadmin'
alias clsweb='rm ~/web/*'

# Hexo
alias loghexo='google-chrome http://localhost:4000'

# Python Server
alias pythonsimpleserver="python -m SimpleHTTPServer"  # 开启8000端口
alias pythonmsimpleserver="python ~/github/shellscript/bin/MySimpleHTTPServer.py"  # 仅开启本地8000端口

##################################################################
## Python 
##################################################################
# ascii 和 char 之间转换
alias pord='test() { python -c "print ord(\"$1\")" };test'  # example: pasc A  # 65
alias pchr='test() { python -c "print chr(int(\"$1\"))" };test'  # example: pchr 65  # A
# 进制转换
alias phex='test() { python -c "print hex(int(\"$1\"))" };test'  # example: phex 16  # 0x10
alias pbin='test() { python -c "print bin(int(\"$1\"))" };test'  # example: pbin 16  # 0b10000
alias poct='test() { python -c "print oct(int(\"$1\"))" };test'  # example: poct 16  # 020
alias pint16='test() { python -c "print int(\"$1\", 16)" };test'  # example: pint16 0x10  # 16

##################################################################
## mysql
##################################################################
alias logmysql='mysql -u root -p'

##################################################################
## player
##################################################################
alias mpa="ls > music.lst && mplayer -playlist music.lst"
alias mps="mplayer -playlist music.lst"
alias mpm="ls > music.lst"

########################################
## cd 相关操作
########################################
alias cddel="cd ~/Documents/thiscandel"
#alias cdhtml="cd /media/coder352/文档/HTML"
alias cdhtml="cd ~/github/Some-Markdown-in-Sublime" 
alias cdjhexo="cd ~/github/jHexo"
alias cdjhexoothers='cd ~/github/others/Blog_backup'
alias cdjhexoqrsync='cd ~/github/jQrsyncHexo'
alias cdjknowledge='cd ~/github/jKnowledge/'
alias cdjpc="cd ~/github/jPC"
alias cdjpcchromeextend='cd ~/github/jPC/src/Chrome_extend/myExtends'
alias cdjpctmux="cd ~/github/jPC/src/tmux"
alias cdjserver="cd ~/github/jServer"
alias cdjtemplate='cd ~/github/jTemplate'
alias cdjtemplatepython="cd ~/github/jTemplate/python"
alias cdjtemplatesql="cd ~/github/jTemplate/sql"
alias cdjtemplatewebjavascript="cd ~/github/jTemplate/web/javascript"
alias cdjtemplatewebjquery="cd ~/github/jTemplate/web/jquery"
alias cdjtemplatewebphp="cd ~/github/jTemplate/web/php"
alias cdjvim="cd ~/github/jvim/vimrc"
alias cdjvimsnippets="cd ~/github/jvim/UltiSnips"
alias cdshare="cd /media/coder352/文档/Share"
alias cdshareshiyanlou="cd /media/coder352/文档/Share/实验楼"
alias cdshellscript="cd ~/github/shellscript"
alias cdshellscripttemplate="cd ~/github/shellscript/template"
alias cdzshshortcuts="cd ~/.oh-my-zsh/plugins"
alias cdvedio="cd /media/coder352/文档/Share/视频"

# snippets for vim
alias cdvimultisnippets='cd ~/.vim/bundle/vim-snippets/UltiSnips/'  # 优先级低
alias cdvimsnippets='cd ~/.vim/bundle/vim-snippets/snippets/'  # 优先级低
# 上面还有一个jvimsnippte

# Windows
alias cdwendang="cd /media/coder352/文档"

##################################################################
## vim 相关操作  进目录是为了退出时能够 git
##################################################################
alias vimms="cd ~/github/shellscript && vim myscript"
alias vimjpcpcconfig="cd ~/github/jPC && vim pc_config"
alias vimjpcchromeconfig="cd ~/github/jPC && vim chrome_config"
alias vimtmuxshorcuts="cd ~/github/jPC/src/tmux && vim README.md"
alias vimzshshortcutgit="cd ~/.oh-my-zsh/plugins/git && vim git.plugins.zsh"
# php.vim 中补全的更新, 中间的括号太乱了
# alias updatephpfunlist='curl http://www.php.net/manual/en/indexes.functions.php | sed '/class="index"/!d' | grep -oP '>[^<]+</a> - .*</li>' | cut -b2- | sed 's~</a> - ~ ; ~; s~</li>$~~' > php-funclist.txt'
# 下面这句话会在当前目录下生成一个 vim 启动时打开文件的顺序以及事件节点, 可以查看是哪里耗费启动时间
# alias vimtimefile = "vim --startuptime timefile the_file_you_want_to_edit"

########################################
## git 相关操作 要被淘汰了 via oh my zsh
########################################
alias gis="git status"
alias gia="git add ."
alias gial='git add --all'
alias gicommit='git commit -m'
alias gilog='git log --oneline --decorate --graph --all'
alias gipush='git push origin master'
alias gid="git diff"
alias gitcloned='git clone --depth=1'  # git shallow clone --depth=1 表示只下载最近一次的版本，使用浅复制可以大大减少下载的数据量
alias gitinfo='git config --global -l'  # 显示git相关配置信息
##### 下面是 Github + Hexo + 七牛云
alias qrsync="~/github/others/qrsync/qrsync"

##################################################################
## Java 
##################################################################
alias javac="javac -J-Dfile.encoding=utf8"

########################################
## SDN
########################################
alias flt="cd ~/github/floodlight/ && java -jar target/floodlight.jar"
alias cnf="cd ~/github/floodlight/src/main/resources/ && cp floodlightdefault.properties.noforwarding floodlightdefault.properties && cd ~"
alias cff="cd ~/github/floodlight/src/main/resources/ && cp floodlightdefault.properties.forwarding floodlightdefault.properties && cd ~"
alias rum="ryu-manager --verbose"
alias cdru="cd ~/github/ryu/ryu/app"
alias cdjtemplatepythonsdnryu="cd ~/github/jTemplate/python/sdn/ryuapp/"
alias cdjtemplatepythonmininet="cd ~/github/jTemplate/python/sdn/mininet"
# ovs-vsctl
alias ovsc='sudo ovs-vsctl'
alias ovscab='sudo ovs-vsctl add-br'
alias ovscdb='sudo ovs-vsctl del-br'
alias ovscap='sudo ovs-vsctl add-port'
alias ovscdp='sudo ovs-vsctl del-port'
alias ovscsc='sudo ovs-vsctl set-controller'

########################################
## SSH 相关操作
########################################
alias sshaliyun="ssh root@115.28.247.19"
alias sshbanwagong="ssh root@45.78.9.29 -p 28484"
alias sshkali="ssh root@192.168.56.105" # passwd: asd
alias sshredhat="ssh root@192.168.56.101" # passwd: 123456
alias sshruanjianbei="ssh jrp@211.87.185.53 -p 22222" # passwd: Yr1Uwud6yH87kcJ8
alias sshteacher="ssh r12@121.251.254.208" # username: root; passwd: 123456
alias sshtencent='ssh root@115.159.88.186'
# alias sshxm="ssh mininet@192.168.56.101" 因为要把本机IP传过去，所以写成可执行文件了
# 很坑的把另一台虚拟机也是192.168.56.101的也设置了sshkey，然后mininet就不能公钥登陆了，还得重设

########################################
## Shadowsocks 后面两个是统计和显示流量
########################################
#alias stass="sudo -S sslocal -c /etc/shadowsocks.json -d start && exit"
alias stass="sudo -S sslocal -c ~/github/jPC/src/shadowsocks.json.bak -d start && exit"
alias stoss="sudo -S sslocal -c ~/github/jPC/src/shadowsocks.json.bak -d stop && exit"
alias stassother="sudo -S sslocal -c ~/github/jPC/src/shadowsocks.json -d start && exit"
alias stossother="sudo -S sslocal -c ~/github/jPC/src/shadowsocks.json -d stop && exit"
#alias stass="echo '$mypassword' | sudo -S sslocal -c /etc/shadowsocks.json -d start && exit"
#alias stoss="echo '$mypassword' | sudo -S sslocal -c /etc/shadowsocks.json -d stop && exit"
#alias cstass="sudo sslocal -s 45.78.9.29 -p 443 -b 127.0.0.1 -l 1080 -k MzBhMDU4YT -m aes-256-cfb -t 500 --fast-open -d start -v"
alias cstass="sudo sslocal -s 45.78.9.29 -p 443 -b 127.0.0.1 -l 1080 -k MzBhMDU4YT -m aes-256-cfb -t 300 -d start -v"
alias cstoss="sudo sslocal -s 45.78.9.29 -p 443 -b 127.0.0.1 -l 1080 -k MzBhMDU4YT -m aes-256-cfb -t 300 -d stop -v"
alias staipt="sudo iptables -I OUTPUT -s 127.0.0.1 -p tcp --sport 1080"
alias showipt="sudo iptables -n -v -L -t filter |grep -i 'spt:1080' |awk -F' ' '{print $2}'"

##################################################################
# Docker
##################################################################
alias doci='docker images'
alias docps='docker ps -a'
alias docpu='docker pull'
alias docr='docker run -it --rm'
alias docs='docker start -i'

########################################
# 渗透 
########################################
#alias sqlmap="python /usr/bin/sqlmap/sqlmap.py"
alias sqlmap="python ~/github/others/sqlmap-dev/sqlmap.py"
alias sqlmapub="python ~/github/others/sqlmap-dev/sqlmap.py --current-user --current-db"

########################################
# 无线AP 
########################################
alias stawf="echo '$mypassword' | sudo ap-hotspot start"
alias stowf="echo '$mypassword' | sudo ap-hotspot stop"

##################################################################
## -s for zsh maybe error in bash
##################################################################
alias -s log=cd # 省去 cd
alias -s html=vi   # 在命令行直接输入后缀为 html 的文件名，会在 vim 中打开,如果想用TextMate打开可以将vi改成mate
alias -s rb=vi     # 在命令行直接输入 ruby 文件，会在 vim 中打开
# alias -s py=vi       # 在命令行直接输入 python 文件，会用 vim 中打开，以下类似
# 被这个 py=vi 坑了好长时间
alias -s js=vi
alias -s c=vi
alias -s java=vi
alias -s txt=vi
alias -s gz='tar -xzvf'  #表示自动解压后缀为 gz 的压缩包。
alias -s tgz='tar -xzvf'
alias -s zip='unzip'
alias -s bz2='tar -xjvf'

# 使用时，前面加$就可以了
# alias sshxm="ssh -X mininet@192.168.56.101" # Mininet 中last 不好用以后会注释掉了
# alias smctcrip="sudo mn --custom ~/topo-2sw-2host.py --topo mytopo --controller=remote,ip=192.168.56.103,port=6653"
# alias smctcrip2="sudo mn --custom ~/topo-2sw-2host.py --topo mytopo --controller=remote,ip=192.168.56.101,port=6653"
# alias fireidx="firefox http://localhost:8080/ui/index.html"
# alias minie="virtualbox --startvm ~/VirtualBox\ VMs/Mininet_Alpha/Mininet_Alpha.vbox & exit"
